### ISSUE TITLE
Retrace Bug

### ISSUE THREAD

**Issue by FaustsDaemon** [HatlessStudios/in-an-instant#25]
Gravitons (and possibly electrons also) are repelling one another in retrace mode. This shouldn't be happening as only the initial force should be inverted. Otherwise, even in continuous time fields, the universe is non-deterministic.

Alex, you said earlier, you couldn't replicate the issue, but I'm 99% sure I'm correct on this one.

**Comment by AlexandreTunstall** [comment]
Duplicate of #19.
